### ISSUE TITLE
Error when opening month year picker then backgrounding app

### ISSUE THREAD

**Issue by FraserCampbell1** [gusparis/react-native-month-year-picker#113]
When I background the app while the month year picker is open I get the following error on Android

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: myapp, PID: 5600
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
        at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1884)
        at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
        at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
        at androidx.fragment.app.DialogFragment.show(DialogFragment.java:260)
        at com.gusparis.monthpicker.RNMPickerModule$1.run(RNMPickerModule.java:46)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
        
  This is on the latest (v1.8.1) version of the code.
  
  Any help is appreciated!

**Comment by FraserCampbell1** [comment]
Upon further investigation this error looks to only get logged in Android 8. However when testing on Android 9 and greater the same issue occurs. 

The scenario is to open the month year picker then background the app. The picker looks to be rendering multiple times and isn't handling the app state changing very well

**Comment by gusparis** [comment]
@FraserCampbell1 I'll take a look at this one 👀

**Comment by debdeep-ganguly** [comment]
@gusparis Any update on the same?
